# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: wangtianxia/temage-backend-test:v1

services:
  - mysql:5.7
  
variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
  - mysql --version
  - echo $PATH
  - ls /root
  - echo "SELECT 'OK';" | mysql -u root -h mysql
  
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
   
build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - cd Django
    - ls -ahl
    - pwd
    - /root/anaconda3/bin/python manage.py cleanmigration --settings Django.ci
    - /root/anaconda3/bin/python manage.py droptablesCI --settings Django.ci
    - /root/anaconda3/bin/python manage.py makemigrations Temage --settings Django.ci
    - /root/anaconda3/bin/python manage.py migrate Temage --settings Django.ci
    - /root/anaconda3/bin/python manage.py test --settings Django.ci
   
deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
